window.ENGLE_PRICE_BOOK = (window.ENGLE_PRICE_BOOK || []).concat([
{ name:"Paint Walls - 2 Coat", trade:"Paint", unit:"SF", retail:2.35, volume:2.10 },
{ name:"Paint Ceiling - 2 Coat", trade:"Paint", unit:"SF", retail:1.85, volume:1.65 },
{ name:"Paint Trim - 2 Coat", trade:"Paint", unit:"LF", retail:2.75, volume:2.40 },
{ name:"Paint Doors - 2 Coat", trade:"Paint", unit:"EA", retail:145, volume:125 },
{ name:"Drywall Patch Small", trade:"Drywall", unit:"EA", retail:95, volume:75 },
{ name:"Drywall Patch Medium", trade:"Drywall", unit:"EA", retail:165, volume:140 },
{ name:"Drywall Patch Large", trade:"Drywall", unit:"EA", retail:285, volume:250 },
{ name:"Replace Interior Door", trade:"Carpentry", unit:"EA", retail:325, volume:275 },
{ name:"Install Baseboard", trade:"Carpentry", unit:"LF", retail:5.50, volume:4.75 },
{ name:"Install Quarter Round", trade:"Carpentry", unit:"LF", retail:3.25, volume:2.75 },
{ name:"Install Cabinet Hardware", trade:"Carpentry", unit:"EA", retail:18, volume:14 },
{ name:"Replace Vanity", trade:"Plumbing", unit:"EA", retail:525, volume:450 },
{ name:"Vanity Install Only", trade:"Plumbing", unit:"EA", retail:275, volume:240 },
{ name:"Replace Faucet", trade:"Plumbing", unit:"EA", retail:185, volume:150 },
{ name:"Replace Toilet (R&R)", trade:"Plumbing", unit:"EA", retail:325, volume:275 },
{ name:"Toilet Install Only", trade:"Plumbing", unit:"EA", retail:195, volume:160 },
{ name:"Install LVP Flooring", trade:"Flooring", unit:"SF", retail:4.85, volume:4.10 },
{ name:"Install Carpet", trade:"Flooring", unit:"SF", retail:3.95, volume:3.35 },
{ name:"Tile Floor Install", trade:"Flooring", unit:"SF", retail:9.75, volume:8.25 },
{ name:"Tile Shower Surround", trade:"Flooring", unit:"SF", retail:18.50, volume:15.75 },
{ name:"Replace Light Fixture", trade:"Electrical", unit:"EA", retail:185, volume:150 },
{ name:"Replace Outlet", trade:"Electrical", unit:"EA", retail:95, volume:75 },
{ name:"Replace Switch", trade:"Electrical", unit:"EA", retail:85, volume:70 },
{ name:"Replace Breaker", trade:"Electrical", unit:"EA", retail:165, volume:135 },
{ name:"Install GFCI Outlet", trade:"Electrical", unit:"EA", retail:135, volume:110 },
{ name:"Roof Shingle Repair", trade:"Roofing", unit:"EA", retail:350, volume:300 },
{ name:"Roof Replacement Asphalt", trade:"Roofing", unit:"SQ", retail:425, volume:375 },
{ name:"Gutter Replacement", trade:"Exterior", unit:"LF", retail:22, volume:18 },
{ name:"Downspout Replacement", trade:"Exterior", unit:"EA", retail:125, volume:95 },
{ name:"Power Wash Exterior", trade:"Exterior", unit:"SF", retail:0.45, volume:0.35 },
{ name:"Window Replacement", trade:"Exterior", unit:"EA", retail:650, volume:575 },
{ name:"Door Replacement Exterior", trade:"Exterior", unit:"EA", retail:950, volume:825 },
{ name:"Demo Interior Room", trade:"Demo", unit:"EA", retail:850, volume:700 },
{ name:"Haul Debris", trade:"Demo", unit:"EA", retail:250, volume:200 },
{ name:"Clean Property Standard", trade:"Cleaning", unit:"EA", retail:325, volume:275 },
{ name:"Deep Clean Property", trade:"Cleaning", unit:"EA", retail:525, volume:450 },
{ name:"HVAC Tune-Up", trade:"HVAC", unit:"EA", retail:185, volume:150 },
{ name:"Replace Furnace", trade:"HVAC", unit:"EA", retail:3200, volume:2850 },
{ name:"Replace AC Unit", trade:"HVAC", unit:"EA", retail:3500, volume:3100 },
{ name:"Install Water Heater", trade:"Plumbing", unit:"EA", retail:1450, volume:1250 },
{ name:"Replace Water Heater", trade:"Plumbing", unit:"EA", retail:1650, volume:1450 },
{ name:"Install Backsplash", trade:"Flooring", unit:"SF", retail:18.75, volume:15.50 },
{ name:"Cabinet Painting", trade:"Paint", unit:"EA", retail:125, volume:105 },
{ name:"Replace Sink", trade:"Plumbing", unit:"EA", retail:285, volume:240 },
{ name:"Install Sink Only", trade:"Plumbing", unit:"EA", retail:185, volume:150 },
{ name:"Replace Disposal", trade:"Plumbing", unit:"EA", retail:225, volume:185 },
{ name:"Install Dishwasher", trade:"Plumbing", unit:"EA", retail:225, volume:185 },
{ name:"Replace Dishwasher", trade:"Plumbing", unit:"EA", retail:285, volume:240 },
{ name:"Install Microwave", trade:"Appliance", unit:"EA", retail:185, volume:150 },
{ name:"Replace Microwave", trade:"Appliance", unit:"EA", retail:225, volume:185 }
]);
