window.ENGLE_PRICE_BOOK = (window.ENGLE_PRICE_BOOK || []).concat([

/* 1 */ { name:"Landscaping - Mulch Installation", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Install mulch beds", spec:"Standard", unit:"CY", baseColumbusPrice:85, volume:88.4, retail:128.18, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 2 */ { name:"Landscaping - Rock Installation", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Install decorative rock", spec:"Standard", unit:"SF", baseColumbusPrice:6, volume:6.24, retail:9.05, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 3 */ { name:"Landscape Bed Edging Installation", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Install edging", spec:"Standard", unit:"LF", baseColumbusPrice:5, volume:5.2, retail:7.54, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 4 */ { name:"Shrub Installation", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Install shrubs", spec:"Standard", unit:"EA", baseColumbusPrice:65, volume:67.6, retail:98.02, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 5 */ { name:"Tree Installation - Small", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Plant small tree", spec:"Standard", unit:"EA", baseColumbusPrice:150, volume:156, retail:226.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 6 */ { name:"Tree Installation - Medium", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Plant medium tree", spec:"Standard", unit:"EA", baseColumbusPrice:350, volume:364, retail:527.8, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 7 */ { name:"Tree Installation - Large", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Plant large tree", spec:"Premium", unit:"EA", baseColumbusPrice:750, volume:780, retail:1131, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 8 */ { name:"Tree Removal - Small", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Remove small tree", spec:"Standard", unit:"EA", baseColumbusPrice:225, volume:234, retail:339.3, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 9 */ { name:"Tree Removal - Medium", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Remove medium tree", spec:"Standard", unit:"EA", baseColumbusPrice:450, volume:468, retail:678.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 10 */ { name:"Tree Removal - Large", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Remove large tree", spec:"Premium", unit:"EA", baseColumbusPrice:950, volume:988, retail:1432.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },

/* 11 */ { name:"Stump Grinding", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Grind tree stump", spec:"Standard", unit:"EA", baseColumbusPrice:150, volume:156, retail:226.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 12 */ { name:"Sod Installation", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Install sod", spec:"Standard", unit:"SF", baseColumbusPrice:2.5, volume:2.6, retail:3.77, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 13 */ { name:"Seeding & Straw", trade:"Exterior", category:"Landscaping", subcategory:"", description:"Seed lawn with straw", spec:"Standard", unit:"SF", baseColumbusPrice:1.5, volume:1.56, retail:2.26, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 14 */ { name:"Drainage - French Drain Install", trade:"Exterior", category:"Drainage", subcategory:"", description:"Install French drain", spec:"Standard", unit:"LF", baseColumbusPrice:35, volume:36.4, retail:52.78, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 15 */ { name:"Drainage - Catch Basin Install", trade:"Exterior", category:"Drainage", subcategory:"", description:"Install catch basin", spec:"Standard", unit:"EA", baseColumbusPrice:450, volume:468, retail:678.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 16 */ { name:"Drainage - Downspout Tie-In", trade:"Exterior", category:"Drainage", subcategory:"", description:"Tie downspout into drainage", spec:"Standard", unit:"EA", baseColumbusPrice:175, volume:182, retail:263.9, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 17 */ { name:"Fence Repair - Wood", trade:"Exterior", category:"Fencing", subcategory:"", description:"Repair wood fence", spec:"Standard", unit:"LF", baseColumbusPrice:12, volume:12.5, retail:18.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 18 */ { name:"Fence Replacement - Wood", trade:"Exterior", category:"Fencing", subcategory:"", description:"Replace wood fence", spec:"Standard", unit:"LF", baseColumbusPrice:25, volume:26, retail:37.7, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 19 */ { name:"Fence Replacement - Vinyl", trade:"Exterior", category:"Fencing", subcategory:"", description:"Replace vinyl fence", spec:"Standard", unit:"LF", baseColumbusPrice:35, volume:36.4, retail:52.78, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 20 */ { name:"Fence Replacement - Aluminum", trade:"Exterior", category:"Fencing", subcategory:"", description:"Replace aluminum fence", spec:"Premium", unit:"LF", baseColumbusPrice:45, volume:46.8, retail:67.86, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 21 */ { name:"Gate Installation - Wood", trade:"Exterior", category:"Fencing", subcategory:"", description:"Install wood gate", spec:"Standard", unit:"EA", baseColumbusPrice:250, volume:260, retail:377, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 22 */ { name:"Gate Installation - Metal", trade:"Exterior", category:"Fencing", subcategory:"", description:"Install metal gate", spec:"Standard", unit:"EA", baseColumbusPrice:350, volume:364, retail:527.8, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 23 */ { name:"Deck Repair - Minor", trade:"Exterior", category:"Deck", subcategory:"", description:"Minor deck repair", spec:"Standard", unit:"SF", baseColumbusPrice:8, volume:8.32, retail:12.06, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 24 */ { name:"Deck Repair - Major", trade:"Exterior", category:"Deck", subcategory:"", description:"Major deck repair", spec:"Standard", unit:"SF", baseColumbusPrice:14, volume:14.56, retail:21.11, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 25 */ { name:"Deck Replacement - Wood", trade:"Exterior", category:"Deck", subcategory:"", description:"Replace wood deck", spec:"Standard", unit:"SF", baseColumbusPrice:25, volume:26, retail:37.7, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },

/* 26 */ { name:"Deck Replacement - Composite", trade:"Exterior", category:"Deck", subcategory:"", description:"Replace composite deck", spec:"Premium", unit:"SF", baseColumbusPrice:45, volume:46.8, retail:67.86, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 27 */ { name:"Deck Staining", trade:"Exterior", category:"Deck", subcategory:"", description:"Stain deck surface", spec:"Standard", unit:"SF", baseColumbusPrice:2.5, volume:2.6, retail:3.77, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 28 */ { name:"Deck Sealing", trade:"Exterior", category:"Deck", subcategory:"", description:"Seal deck surface", spec:"Standard", unit:"SF", baseColumbusPrice:2, volume:2.08, retail:3.02, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 29 */ { name:"Pergola Installation", trade:"Exterior", category:"Outdoor Structures", subcategory:"", description:"Install pergola", spec:"Standard", unit:"EA", baseColumbusPrice:1800, volume:1872, retail:2714.4, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 30 */ { name:"Gazebo Installation", trade:"Exterior", category:"Outdoor Structures", subcategory:"", description:"Install gazebo", spec:"Premium", unit:"EA", baseColumbusPrice:2500, volume:2600, retail:3770, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },

/* 31 */ { name:"Outdoor Kitchen Installation", trade:"Exterior", category:"Outdoor Structures", subcategory:"", description:"Install outdoor kitchen", spec:"Premium", unit:"EA", baseColumbusPrice:6500, volume:6760, retail:9802, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 32 */ { name:"Patio Installation - Concrete", trade:"Exterior", category:"Hardscape", subcategory:"", description:"Install concrete patio", spec:"Standard", unit:"SF", baseColumbusPrice:12, volume:12.5, retail:18.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 33 */ { name:"Patio Installation - Paver", trade:"Exterior", category:"Hardscape", subcategory:"", description:"Install paver patio", spec:"Premium", unit:"SF", baseColumbusPrice:18, volume:18.7, retail:27.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 34 */ { name:"Patio Repair - Minor", trade:"Exterior", category:"Hardscape", subcategory:"", description:"Repair patio minor", spec:"Standard", unit:"SF", baseColumbusPrice:8, volume:8.32, retail:12.06, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 35 */ { name:"Patio Repair - Major", trade:"Exterior", category:"Hardscape", subcategory:"", description:"Repair patio major", spec:"Standard", unit:"SF", baseColumbusPrice:14, volume:14.56, retail:21.11, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 36 */ { name:"Retaining Wall - Block", trade:"Exterior", category:"Hardscape", subcategory:"", description:"Install block retaining wall", spec:"Standard", unit:"SF", baseColumbusPrice:25, volume:26, retail:37.7, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 37 */ { name:"Retaining Wall - Stone", trade:"Exterior", category:"Hardscape", subcategory:"", description:"Install stone retaining wall", spec:"Premium", unit:"SF", baseColumbusPrice:45, volume:46.8, retail:67.86, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 38 */ { name:"Walkway Installation - Concrete", trade:"Exterior", category:"Hardscape", subcategory:"", description:"Install concrete walkway", spec:"Standard", unit:"SF", baseColumbusPrice:10, volume:10.4, retail:15.08, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 39 */ { name:"Walkway Installation - Paver", trade:"Exterior", category:"Hardscape", subcategory:"", description:"Install paver walkway", spec:"Premium", unit:"SF", baseColumbusPrice:16, volume:16.64, retail:24.13, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 40 */ { name:"Walkway Repair", trade:"Exterior", category:"Hardscape", subcategory:"", description:"Repair walkway", spec:"Standard", unit:"SF", baseColumbusPrice:8, volume:8.32, retail:12.06, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 41 */ { name:"Pressure Washing - House Exterior", trade:"Exterior", category:"Cleaning", subcategory:"", description:"Pressure wash house exterior", spec:"Standard", unit:"SF", baseColumbusPrice:0.35, volume:0.36, retail:0.52, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 42 */ { name:"Pressure Washing - Driveway", trade:"Exterior", category:"Cleaning", subcategory:"", description:"Pressure wash driveway", spec:"Standard", unit:"SF", baseColumbusPrice:0.3, volume:0.31, retail:0.45, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 43 */ { name:"Pressure Washing - Deck", trade:"Exterior", category:"Cleaning", subcategory:"", description:"Pressure wash deck", spec:"Standard", unit:"SF", baseColumbusPrice:0.4, volume:0.42, retail:0.61, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 44 */ { name:"Power Washing - Roof Soft Wash", trade:"Roofing", category:"Cleaning", subcategory:"", description:"Soft wash roof", spec:"Standard", unit:"SF", baseColumbusPrice:0.5, volume:0.52, retail:0.75, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 45 */ { name:"Window Cleaning - Interior", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Clean interior windows", spec:"Standard", unit:"EA", baseColumbusPrice:5, volume:5.2, retail:7.54, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 46 */ { name:"Window Cleaning - Exterior", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Clean exterior windows", spec:"Standard", unit:"EA", baseColumbusPrice:6, volume:6.24, retail:9.05, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 47 */ { name:"Full House Cleaning - Standard", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Standard house cleaning", spec:"Standard", unit:"EA", baseColumbusPrice:250, volume:260, retail:377, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 48 */ { name:"Full House Cleaning - Deep Clean", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Deep clean house", spec:"Premium", unit:"EA", baseColumbusPrice:450, volume:468, retail:678.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 49 */ { name:"Post Construction Cleaning", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Clean after construction", spec:"Premium", unit:"EA", baseColumbusPrice:650, volume:676, retail:980.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 50 */ { name:"Move-Out Cleaning", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Move-out cleaning service", spec:"Standard", unit:"EA", baseColumbusPrice:300, volume:312, retail:452.4, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 51 */ { name:"Trash Out - Light", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Remove light debris", spec:"Standard", unit:"EA", baseColumbusPrice:150, volume:156, retail:226.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 52 */ { name:"Trash Out - Moderate", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Remove moderate debris", spec:"Standard", unit:"EA", baseColumbusPrice:350, volume:364, retail:527.8, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 53 */ { name:"Trash Out - Heavy", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Remove heavy debris", spec:"Premium", unit:"EA", baseColumbusPrice:750, volume:780, retail:1131, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 54 */ { name:"Junk Removal - Appliance", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Remove appliance", spec:"Standard", unit:"EA", baseColumbusPrice:125, volume:130, retail:188.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 55 */ { name:"Junk Removal - Furniture", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Remove furniture", spec:"Standard", unit:"EA", baseColumbusPrice:150, volume:156, retail:226.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 56 */ { name:"Junk Removal - Full Load", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Remove full truck load", spec:"Premium", unit:"EA", baseColumbusPrice:650, volume:676, retail:980.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 57 */ { name:"Dumpster Rental - 10 Yard", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"10 yard dumpster", spec:"Standard", unit:"EA", baseColumbusPrice:350, volume:364, retail:527.8, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 58 */ { name:"Dumpster Rental - 20 Yard", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"20 yard dumpster", spec:"Standard", unit:"EA", baseColumbusPrice:450, volume:468, retail:678.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 59 */ { name:"Dumpster Rental - 30 Yard", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"30 yard dumpster", spec:"Standard", unit:"EA", baseColumbusPrice:550, volume:572, retail:829.4, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 60 */ { name:"Final Job Site Cleanup", trade:"Cleaning", category:"Cleaning", subcategory:"", description:"Final cleanup service", spec:"Standard", unit:"EA", baseColumbusPrice:225, volume:234, retail:339.3, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 61 */ { name:"Interior Touch-Up Painting", trade:"Painting", category:"Painting", subcategory:"", description:"Minor interior paint touch-up", spec:"Standard", unit:"EA", baseColumbusPrice:150, volume:156, retail:226.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 62 */ { name:"Drywall Patch - Small", trade:"Drywall", category:"Drywall", subcategory:"", description:"Patch small drywall hole", spec:"Standard", unit:"EA", baseColumbusPrice:85, volume:88.4, retail:128.18, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 63 */ { name:"Drywall Patch - Medium", trade:"Drywall", category:"Drywall", subcategory:"", description:"Patch medium drywall damage", spec:"Standard", unit:"EA", baseColumbusPrice:150, volume:156, retail:226.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 64 */ { name:"Drywall Patch - Large", trade:"Drywall", category:"Drywall", subcategory:"", description:"Patch large drywall damage", spec:"Standard", unit:"EA", baseColumbusPrice:275, volume:286, retail:414.7, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 65 */ { name:"Drywall Full Sheet Replacement", trade:"Drywall", category:"Drywall", subcategory:"", description:"Replace full drywall sheet", spec:"Standard", unit:"EA", baseColumbusPrice:125, volume:130, retail:188.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 66 */ { name:"Texture Matching - Drywall", trade:"Drywall", category:"Drywall", subcategory:"", description:"Match drywall texture", spec:"Standard", unit:"EA", baseColumbusPrice:125, volume:130, retail:188.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 67 */ { name:"Interior Caulking - General", trade:"Interior", category:"Interior", subcategory:"", description:"General interior caulking", spec:"Standard", unit:"LF", baseColumbusPrice:2.25, volume:2.34, retail:3.39, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 68 */ { name:"Interior Trim Installation", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Install interior trim", spec:"Standard", unit:"LF", baseColumbusPrice:10, volume:10.4, retail:15.08, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 69 */ { name:"Interior Trim Repair", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Repair trim", spec:"Standard", unit:"LF", baseColumbusPrice:6, volume:6.24, retail:9.05, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 70 */ { name:"Baseboard Replacement", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Replace baseboards", spec:"Standard", unit:"LF", baseColumbusPrice:12, volume:12.5, retail:18.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 71 */ { name:"Crown Molding Installation", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Install crown molding", spec:"Premium", unit:"LF", baseColumbusPrice:18, volume:18.7, retail:27.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 72 */ { name:"Cabinet Adjustment", trade:"Carpentry", category:"Cabinetry", subcategory:"", description:"Adjust cabinet doors/drawers", spec:"Standard", unit:"EA", baseColumbusPrice:45, volume:46.8, retail:67.86, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 73 */ { name:"Cabinet Hardware Replacement", trade:"Carpentry", category:"Cabinetry", subcategory:"", description:"Replace cabinet hardware", spec:"Standard", unit:"EA", baseColumbusPrice:15, volume:15.6, retail:22.62, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 74 */ { name:"Cabinet Door Replacement", trade:"Carpentry", category:"Cabinetry", subcategory:"", description:"Replace cabinet door", spec:"Standard", unit:"EA", baseColumbusPrice:125, volume:130, retail:188.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 75 */ { name:"Cabinet Box Replacement", trade:"Carpentry", category:"Cabinetry", subcategory:"", description:"Replace cabinet box", spec:"Premium", unit:"EA", baseColumbusPrice:350, volume:364, retail:527.8, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 76 */ { name:"Closet Shelf Installation", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Install closet shelving", spec:"Standard", unit:"LF", baseColumbusPrice:12, volume:12.5, retail:18.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 77 */ { name:"Closet Rod Installation", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Install closet rod", spec:"Standard", unit:"EA", baseColumbusPrice:45, volume:46.8, retail:67.86, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 78 */ { name:"Door Stop Installation", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Install door stop", spec:"Standard", unit:"EA", baseColumbusPrice:15, volume:15.6, retail:22.62, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 79 */ { name:"Smoke Detector Replacement", trade:"Electrical", category:"Electrical", subcategory:"", description:"Replace smoke detector", spec:"Standard", unit:"EA", baseColumbusPrice:65, volume:67.6, retail:98.02, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 80 */ { name:"Carbon Monoxide Detector Install", trade:"Electrical", category:"Electrical", subcategory:"", description:"Install CO detector", spec:"Standard", unit:"EA", baseColumbusPrice:75, volume:78, retail:113.1, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 81 */ { name:"Light Bulb Replacement", trade:"Electrical", category:"Electrical", subcategory:"", description:"Replace light bulbs", spec:"Standard", unit:"EA", baseColumbusPrice:8, volume:8.32, retail:12.06, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 82 */ { name:"HVAC Filter Replacement", trade:"HVAC", category:"HVAC", subcategory:"", description:"Replace HVAC filter", spec:"Standard", unit:"EA", baseColumbusPrice:25, volume:26, retail:37.7, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 83 */ { name:"Thermostat Replacement - Basic", trade:"HVAC", category:"HVAC", subcategory:"", description:"Replace basic thermostat", spec:"Standard", unit:"EA", baseColumbusPrice:125, volume:130, retail:188.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 84 */ { name:"Thermostat Replacement - Smart", trade:"HVAC", category:"HVAC", subcategory:"", description:"Install smart thermostat", spec:"Premium", unit:"EA", baseColumbusPrice:275, volume:286, retail:414.7, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 85 */ { name:"HVAC Tune-Up", trade:"HVAC", category:"HVAC", subcategory:"", description:"HVAC system tune-up", spec:"Standard", unit:"EA", baseColumbusPrice:150, volume:156, retail:226.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 86 */ { name:"Plumbing Leak Repair", trade:"Plumbing", category:"Plumbing", subcategory:"", description:"Repair plumbing leak", spec:"Standard", unit:"EA", baseColumbusPrice:175, volume:182, retail:263.9, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 87 */ { name:"Water Shutoff Valve Replacement", trade:"Plumbing", category:"Plumbing", subcategory:"", description:"Replace shutoff valve", spec:"Standard", unit:"EA", baseColumbusPrice:125, volume:130, retail:188.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 88 */ { name:"Toilet Install - New Location", trade:"Plumbing", category:"Plumbing", subcategory:"", description:"Install new toilet location", spec:"Standard", unit:"EA", baseColumbusPrice:650, volume:676, retail:980.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 89 */ { name:"Toilet Replace - Remove & Replace", trade:"Plumbing", category:"Plumbing", subcategory:"", description:"Remove and replace toilet", spec:"Standard", unit:"EA", baseColumbusPrice:275, volume:286, retail:414.7, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 90 */ { name:"Vanity Installation - Standard", trade:"Plumbing", category:"Bathroom", subcategory:"", description:"Install bathroom vanity", spec:"Standard", unit:"EA", baseColumbusPrice:450, volume:468, retail:678.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 91 */ { name:"Vanity Installation - Premium", trade:"Plumbing", category:"Bathroom", subcategory:"", description:"Install premium vanity", spec:"Premium", unit:"EA", baseColumbusPrice:750, volume:780, retail:1131, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false }

]);
