window.ENGLE_PRICE_BOOK = (window.ENGLE_PRICE_BOOK || []).concat([

/* 1 */ { name:"Window Glass Replacement - Single Pane", trade:"Glass", category:"Glass", subcategory:"", description:"Replace single pane glass", spec:"Standard", unit:"EA", baseColumbusPrice:125, volume:130, retail:188.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 2 */ { name:"Window Glass Replacement - Double Pane", trade:"Glass", category:"Glass", subcategory:"", description:"Replace double pane glass", spec:"Insulated", unit:"EA", baseColumbusPrice:225, volume:234, retail:339.3, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 3 */ { name:"Window Lock Replacement", trade:"Windows", category:"Windows", subcategory:"", description:"Replace window lock", spec:"Standard", unit:"EA", baseColumbusPrice:35, volume:36.4, retail:52.78, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 4 */ { name:"Window Balance Replacement", trade:"Windows", category:"Windows", subcategory:"", description:"Replace window balance system", spec:"Standard", unit:"EA", baseColumbusPrice:75, volume:78, retail:113.1, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 5 */ { name:"Window Track Cleaning & Repair", trade:"Windows", category:"Windows", subcategory:"", description:"Clean and adjust window track", spec:"Standard", unit:"EA", baseColumbusPrice:45, volume:46.8, retail:67.86, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 6 */ { name:"Window Screen Repair", trade:"Windows", category:"Windows", subcategory:"", description:"Repair window screen", spec:"Standard", unit:"EA", baseColumbusPrice:25, volume:26, retail:37.7, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 7 */ { name:"Window Screen Replacement - Custom", trade:"Windows", category:"Windows", subcategory:"", description:"Replace custom window screen", spec:"Standard", unit:"EA", baseColumbusPrice:45, volume:46.8, retail:67.86, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 8 */ { name:"Window Trim Repair - Interior", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Repair interior window trim", spec:"Standard", unit:"LF", baseColumbusPrice:12, volume:12.5, retail:18.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 9 */ { name:"Window Trim Replacement - Interior", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Replace interior trim", spec:"Standard", unit:"LF", baseColumbusPrice:18, volume:18.7, retail:27.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 10 */ { name:"Window Caulking - Exterior", trade:"Exterior", category:"Exterior", subcategory:"", description:"Caulk window perimeter", spec:"Standard", unit:"LF", baseColumbusPrice:2.25, volume:2.34, retail:3.39, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 11 */ { name:"Window Flashing Repair", trade:"Exterior", category:"Exterior", subcategory:"", description:"Repair window flashing", spec:"Standard", unit:"EA", baseColumbusPrice:150, volume:156, retail:226.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 12 */ { name:"Window Replacement - Vinyl", trade:"Windows", category:"Windows", subcategory:"", description:"Install vinyl window", spec:"Standard", unit:"EA", baseColumbusPrice:450, volume:468, retail:678.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 13 */ { name:"Window Replacement - Wood", trade:"Windows", category:"Windows", subcategory:"", description:"Install wood window", spec:"Premium", unit:"EA", baseColumbusPrice:750, volume:780, retail:1131, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 14 */ { name:"Window Replacement - Egress", trade:"Windows", category:"Windows", subcategory:"", description:"Install egress window", spec:"Code Compliant", unit:"EA", baseColumbusPrice:2500, volume:2600, retail:3770, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 15 */ { name:"Window Well Installation", trade:"Exterior", category:"Exterior", subcategory:"", description:"Install window well", spec:"Standard", unit:"EA", baseColumbusPrice:650, volume:676, retail:980.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },

/* 16 */ { name:"Window Well Cover Installation", trade:"Exterior", category:"Exterior", subcategory:"", description:"Install window well cover", spec:"Standard", unit:"EA", baseColumbusPrice:150, volume:156, retail:226.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 17 */ { name:"Wood Rot Repair - Window Frame", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Repair wood rot", spec:"Standard", unit:"EA", baseColumbusPrice:225, volume:234, retail:339.3, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 18 */ { name:"Weatherstripping Replacement - Door", trade:"Doors", category:"Doors", subcategory:"", description:"Replace door weatherstripping", spec:"Standard", unit:"EA", baseColumbusPrice:75, volume:78, retail:113.1, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 19 */ { name:"Weatherstripping Replacement - Window", trade:"Windows", category:"Windows", subcategory:"", description:"Replace window weatherstripping", spec:"Standard", unit:"EA", baseColumbusPrice:55, volume:57, retail:82.65, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 20 */ { name:"Siding Repair - Minor", trade:"Exterior", category:"Exterior", subcategory:"", description:"Repair small siding section", spec:"Standard", unit:"SF", baseColumbusPrice:8, volume:8.32, retail:12.06, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 21 */ { name:"Siding Repair - Major", trade:"Exterior", category:"Exterior", subcategory:"", description:"Repair large siding section", spec:"Standard", unit:"SF", baseColumbusPrice:14, volume:14.56, retail:21.11, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 22 */ { name:"Siding Replacement - Vinyl", trade:"Exterior", category:"Exterior", subcategory:"", description:"Replace vinyl siding", spec:"Standard", unit:"SF", baseColumbusPrice:10, volume:10.4, retail:15.08, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 23 */ { name:"Siding Replacement - Fiber Cement", trade:"Exterior", category:"Exterior", subcategory:"", description:"Replace fiber cement siding", spec:"Premium", unit:"SF", baseColumbusPrice:14, volume:14.56, retail:21.11, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 24 */ { name:"Siding Replacement - Wood", trade:"Exterior", category:"Exterior", subcategory:"", description:"Replace wood siding", spec:"Premium", unit:"SF", baseColumbusPrice:16, volume:16.64, retail:24.13, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 25 */ { name:"Siding Power Wash Prep", trade:"Exterior", category:"Exterior", subcategory:"", description:"Prep siding for paint", spec:"Standard", unit:"SF", baseColumbusPrice:0.35, volume:0.36, retail:0.52, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 26 */ { name:"Siding Caulking", trade:"Exterior", category:"Exterior", subcategory:"", description:"Seal siding joints", spec:"Standard", unit:"LF", baseColumbusPrice:2.25, volume:2.34, retail:3.39, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 27 */ { name:"Soffit Repair", trade:"Exterior", category:"Exterior", subcategory:"", description:"Repair soffit", spec:"Standard", unit:"SF", baseColumbusPrice:10, volume:10.4, retail:15.08, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 28 */ { name:"Fascia Board Replacement", trade:"Exterior", category:"Exterior", subcategory:"", description:"Replace fascia", spec:"Standard", unit:"LF", baseColumbusPrice:12, volume:12.5, retail:18.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 29 */ { name:"Exterior Wood Trim Replacement", trade:"Exterior", category:"Exterior", subcategory:"", description:"Replace exterior trim", spec:"Standard", unit:"LF", baseColumbusPrice:14, volume:14.56, retail:21.11, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 30 */ { name:"Exterior Wood Trim Repair", trade:"Exterior", category:"Exterior", subcategory:"", description:"Repair exterior trim", spec:"Standard", unit:"LF", baseColumbusPrice:10, volume:10.4, retail:15.08, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false }

/* 31 */ { name:"Exterior Door Replacement - Steel", trade:"Doors", category:"Doors", subcategory:"Exterior", description:"Install steel exterior door", spec:"Standard", unit:"EA", baseColumbusPrice:650, volume:676, retail:980.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 32 */ { name:"Exterior Door Replacement - Fiberglass", trade:"Doors", category:"Doors", subcategory:"Exterior", description:"Install fiberglass exterior door", spec:"Premium", unit:"EA", baseColumbusPrice:850, volume:884, retail:1281.8, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 33 */ { name:"Exterior Door Replacement - Wood", trade:"Doors", category:"Doors", subcategory:"Exterior", description:"Install wood exterior door", spec:"Premium", unit:"EA", baseColumbusPrice:950, volume:988, retail:1432.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 34 */ { name:"Interior Door Replacement - Hollow Core", trade:"Doors", category:"Doors", subcategory:"Interior", description:"Replace hollow core interior door", spec:"Standard", unit:"EA", baseColumbusPrice:225, volume:234, retail:339.3, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 35 */ { name:"Interior Door Replacement - Solid Core", trade:"Doors", category:"Doors", subcategory:"Interior", description:"Replace solid core interior door", spec:"Premium", unit:"EA", baseColumbusPrice:325, volume:338, retail:489.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 36 */ { name:"Door Frame Repair", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Repair damaged door frame", spec:"Standard", unit:"EA", baseColumbusPrice:175, volume:182, retail:263.9, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 37 */ { name:"Door Frame Replacement", trade:"Carpentry", category:"Carpentry", subcategory:"", description:"Replace door frame", spec:"Standard", unit:"EA", baseColumbusPrice:325, volume:338, retail:489.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 38 */ { name:"Door Hardware Replacement - Basic", trade:"Doors", category:"Doors", subcategory:"", description:"Replace door hardware set", spec:"Standard", unit:"EA", baseColumbusPrice:95, volume:99, retail:143.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 39 */ { name:"Door Hardware Replacement - Premium", trade:"Doors", category:"Doors", subcategory:"", description:"Replace premium hardware", spec:"Premium", unit:"EA", baseColumbusPrice:185, volume:192, retail:278.4, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 40 */ { name:"Deadbolt Installation", trade:"Doors", category:"Doors", subcategory:"", description:"Install deadbolt lock", spec:"Standard", unit:"EA", baseColumbusPrice:85, volume:88.4, retail:128.18, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 41 */ { name:"Door Threshold Replacement", trade:"Doors", category:"Doors", subcategory:"", description:"Replace door threshold", spec:"Standard", unit:"EA", baseColumbusPrice:125, volume:130, retail:188.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 42 */ { name:"Sliding Glass Door Repair", trade:"Doors", category:"Doors", subcategory:"", description:"Repair sliding glass door", spec:"Standard", unit:"EA", baseColumbusPrice:275, volume:286, retail:414.7, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 43 */ { name:"Sliding Glass Door Replacement", trade:"Doors", category:"Doors", subcategory:"", description:"Replace sliding glass door", spec:"Standard", unit:"EA", baseColumbusPrice:1450, volume:1508, retail:2186.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 44 */ { name:"Garage Door Panel Replacement", trade:"Garage", category:"Garage", subcategory:"", description:"Replace damaged garage panel", spec:"Standard", unit:"EA", baseColumbusPrice:250, volume:260, retail:377, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 45 */ { name:"Garage Door Spring Replacement", trade:"Garage", category:"Garage", subcategory:"", description:"Replace garage door springs", spec:"Standard", unit:"EA", baseColumbusPrice:225, volume:234, retail:339.3, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 46 */ { name:"Garage Door Opener Replacement", trade:"Garage", category:"Garage", subcategory:"", description:"Replace garage opener", spec:"Standard", unit:"EA", baseColumbusPrice:375, volume:390, retail:565.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 47 */ { name:"Garage Door Track Repair", trade:"Garage", category:"Garage", subcategory:"", description:"Repair garage track system", spec:"Standard", unit:"EA", baseColumbusPrice:150, volume:156, retail:226.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 48 */ { name:"Garage Door Cable Replacement", trade:"Garage", category:"Garage", subcategory:"", description:"Replace garage door cables", spec:"Standard", unit:"EA", baseColumbusPrice:165, volume:171.6, retail:249.0, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 49 */ { name:"Garage Door Full Replacement", trade:"Garage", category:"Garage", subcategory:"", description:"Install new garage door", spec:"Standard", unit:"EA", baseColumbusPrice:1450, volume:1508, retail:2186.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 50 */ { name:"Attic Insulation - Blow In", trade:"Insulation", category:"Insulation", subcategory:"", description:"Blow-in attic insulation", spec:"Standard", unit:"SF", baseColumbusPrice:1.75, volume:1.82, retail:2.64, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 51 */ { name:"Attic Insulation - Batt", trade:"Insulation", category:"Insulation", subcategory:"", description:"Install batt insulation", spec:"Standard", unit:"SF", baseColumbusPrice:2.25, volume:2.34, retail:3.39, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 52 */ { name:"Wall Insulation - Fiberglass", trade:"Insulation", category:"Insulation", subcategory:"", description:"Install wall insulation", spec:"Standard", unit:"SF", baseColumbusPrice:2.5, volume:2.6, retail:3.77, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 53 */ { name:"Wall Insulation - Spray Foam", trade:"Insulation", category:"Insulation", subcategory:"", description:"Install spray foam insulation", spec:"Premium", unit:"SF", baseColumbusPrice:4.5, volume:4.68, retail:6.79, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 54 */ { name:"Crawlspace Insulation", trade:"Insulation", category:"Insulation", subcategory:"", description:"Install crawlspace insulation", spec:"Standard", unit:"SF", baseColumbusPrice:2.75, volume:2.86, retail:4.15, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 55 */ { name:"Duct Insulation Wrap", trade:"HVAC", category:"HVAC", subcategory:"", description:"Wrap HVAC ducts", spec:"Standard", unit:"LF", baseColumbusPrice:6, volume:6.24, retail:9.05, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 56 */ { name:"Air Sealing - Whole House", trade:"Energy", category:"Energy", subcategory:"", description:"Seal air leaks", spec:"Standard", unit:"EA", baseColumbusPrice:450, volume:468, retail:678.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 57 */ { name:"Weatherization Package", trade:"Energy", category:"Energy", subcategory:"", description:"Full weatherization service", spec:"Standard", unit:"EA", baseColumbusPrice:850, volume:884, retail:1281.8, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 58 */ { name:"Gutter Cleaning", trade:"Exterior", category:"Exterior", subcategory:"", description:"Clean gutters", spec:"Standard", unit:"LF", baseColumbusPrice:1.5, volume:1.56, retail:2.26, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 59 */ { name:"Gutter Repair", trade:"Exterior", category:"Exterior", subcategory:"", description:"Repair gutters", spec:"Standard", unit:"LF", baseColumbusPrice:4, volume:4.16, retail:6.03, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 60 */ { name:"Gutter Replacement - Aluminum", trade:"Exterior", category:"Exterior", subcategory:"", description:"Replace aluminum gutters", spec:"Standard", unit:"LF", baseColumbusPrice:12, volume:12.5, retail:18.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 61 */ { name:"Gutter Replacement - Copper", trade:"Exterior", category:"Exterior", subcategory:"", description:"Replace copper gutters", spec:"Premium", unit:"LF", baseColumbusPrice:28, volume:29.1, retail:42.22, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 62 */ { name:"Downspout Replacement", trade:"Exterior", category:"Exterior", subcategory:"", description:"Replace downspouts", spec:"Standard", unit:"LF", baseColumbusPrice:10, volume:10.4, retail:15.08, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 63 */ { name:"Downspout Extension Install", trade:"Exterior", category:"Exterior", subcategory:"", description:"Install downspout extension", spec:"Standard", unit:"EA", baseColumbusPrice:35, volume:36.4, retail:52.78, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 64 */ { name:"Gutter Guard Installation", trade:"Exterior", category:"Exterior", subcategory:"", description:"Install gutter guards", spec:"Standard", unit:"LF", baseColumbusPrice:9, volume:9.36, retail:13.57, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 65 */ { name:"Roof Inspection", trade:"Roofing", category:"Roofing", subcategory:"", description:"General roof inspection", spec:"Standard", unit:"EA", baseColumbusPrice:125, volume:130, retail:188.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 66 */ { name:"Roof Repair - Minor", trade:"Roofing", category:"Roofing", subcategory:"", description:"Minor roof repair", spec:"Standard", unit:"EA", baseColumbusPrice:225, volume:234, retail:339.3, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 67 */ { name:"Roof Repair - Moderate", trade:"Roofing", category:"Roofing", subcategory:"", description:"Moderate roof repair", spec:"Standard", unit:"EA", baseColumbusPrice:450, volume:468, retail:678.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 68 */ { name:"Roof Repair - Major", trade:"Roofing", category:"Roofing", subcategory:"", description:"Major roof repair", spec:"Standard", unit:"EA", baseColumbusPrice:850, volume:884, retail:1281.8, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 69 */ { name:"Roof Replacement - Asphalt Shingles", trade:"Roofing", category:"Roofing", subcategory:"", description:"Replace asphalt shingle roof", spec:"Standard", unit:"SQ", baseColumbusPrice:350, volume:364, retail:527.8, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 70 */ { name:"Roof Replacement - Metal", trade:"Roofing", category:"Roofing", subcategory:"", description:"Replace metal roof", spec:"Premium", unit:"SQ", baseColumbusPrice:700, volume:728, retail:1055.6, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },

/* 71 */ { name:"Roof Replacement - Flat Membrane", trade:"Roofing", category:"Roofing", subcategory:"", description:"Replace flat membrane roof", spec:"Premium", unit:"SQ", baseColumbusPrice:600, volume:624, retail:904.8, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 72 */ { name:"Chimney Flashing Repair", trade:"Roofing", category:"Roofing", subcategory:"", description:"Repair chimney flashing", spec:"Standard", unit:"EA", baseColumbusPrice:275, volume:286, retail:414.7, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 73 */ { name:"Chimney Cap Replacement", trade:"Roofing", category:"Roofing", subcategory:"", description:"Replace chimney cap", spec:"Standard", unit:"EA", baseColumbusPrice:185, volume:192, retail:278.4, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 74 */ { name:"Roof Vent Replacement", trade:"Roofing", category:"Roofing", subcategory:"", description:"Replace roof vent", spec:"Standard", unit:"EA", baseColumbusPrice:95, volume:99, retail:143.5, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 75 */ { name:"Ridge Vent Installation", trade:"Roofing", category:"Roofing", subcategory:"", description:"Install ridge vent", spec:"Standard", unit:"LF", baseColumbusPrice:12, volume:12.5, retail:18.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 76 */ { name:"Skylight Repair", trade:"Roofing", category:"Roofing", subcategory:"", description:"Repair skylight", spec:"Standard", unit:"EA", baseColumbusPrice:225, volume:234, retail:339.3, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 77 */ { name:"Skylight Replacement", trade:"Roofing", category:"Roofing", subcategory:"", description:"Replace skylight", spec:"Standard", unit:"EA", baseColumbusPrice:650, volume:676, retail:980.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 78 */ { name:"Roof Deck Repair", trade:"Roofing", category:"Roofing", subcategory:"", description:"Repair roof decking", spec:"Standard", unit:"SF", baseColumbusPrice:6, volume:6.24, retail:9.05, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 79 */ { name:"Ice & Water Shield Installation", trade:"Roofing", category:"Roofing", subcategory:"", description:"Install ice & water shield", spec:"Standard", unit:"SF", baseColumbusPrice:2.5, volume:2.6, retail:3.77, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 80 */ { name:"Roof Tear-Off & Disposal", trade:"Roofing", category:"Roofing", subcategory:"", description:"Remove and dispose roofing", spec:"Standard", unit:"SQ", baseColumbusPrice:150, volume:156, retail:226.2, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },

/* 81 */ { name:"Concrete Crack Repair", trade:"Concrete", category:"Concrete", subcategory:"", description:"Repair concrete cracks", spec:"Standard", unit:"LF", baseColumbusPrice:8, volume:8.32, retail:12.06, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 82 */ { name:"Concrete Patch Repair", trade:"Concrete", category:"Concrete", subcategory:"", description:"Patch damaged concrete", spec:"Standard", unit:"SF", baseColumbusPrice:10, volume:10.4, retail:15.08, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 83 */ { name:"Concrete Slab Pour", trade:"Concrete", category:"Concrete", subcategory:"", description:"Pour concrete slab", spec:"Standard", unit:"SF", baseColumbusPrice:12, volume:12.5, retail:18.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 84 */ { name:"Concrete Driveway Replacement", trade:"Concrete", category:"Concrete", subcategory:"", description:"Replace driveway", spec:"Standard", unit:"SF", baseColumbusPrice:14, volume:14.56, retail:21.11, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 85 */ { name:"Concrete Sidewalk Replacement", trade:"Concrete", category:"Concrete", subcategory:"", description:"Replace sidewalk", spec:"Standard", unit:"SF", baseColumbusPrice:12, volume:12.5, retail:18.12, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },

/* 86 */ { name:"Concrete Steps Replacement", trade:"Concrete", category:"Concrete", subcategory:"", description:"Replace steps", spec:"Standard", unit:"EA", baseColumbusPrice:850, volume:884, retail:1281.8, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:true },
/* 87 */ { name:"Concrete Sealing", trade:"Concrete", category:"Concrete", subcategory:"", description:"Seal concrete surface", spec:"Standard", unit:"SF", baseColumbusPrice:1.5, volume:1.56, retail:2.26, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 88 */ { name:"Concrete Grinding", trade:"Concrete", category:"Concrete", subcategory:"", description:"Grind uneven concrete", spec:"Standard", unit:"SF", baseColumbusPrice:4, volume:4.16, retail:6.03, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 89 */ { name:"Concrete Leveling", trade:"Concrete", category:"Concrete", subcategory:"", description:"Level sunken concrete", spec:"Standard", unit:"SF", baseColumbusPrice:6, volume:6.24, retail:9.05, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false },
/* 90 */ { name:"Concrete Demo & Haul Away", trade:"Concrete", category:"Concrete", subcategory:"", description:"Demolish and remove concrete", spec:"Standard", unit:"SF", baseColumbusPrice:8, volume:8.32, retail:12.06, source:"LIVE Gap Fill", reviewFlag:"", quoteRequired:false }

]);
